<<<<<<< HEAD
version: "3.1"
services:
  frontend:
    build:
      context: ./
      dockerfile: client/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on: 
      - backend
  backend:
    build:
      context: ./
      dockerfile: server/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
=======
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:13
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
>>>>>>> 3d574adcc23950f8dbb0a3eabe8f825f2f819047
