export const GET_ASSIGNMENT = 'GET_ASSIGNMENT';
export const EDIT_ASSIGNMENT = 'EDIT_ASSIGNMENT';
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';

export const ASSIGNMENT_ADD_RESOURCE = 'ASSIGNMENT_ADD_RESOURCE';
export const ASSIGNMENT_EDIT_RESOURCE = 'ASSIGNMENT_EDIT_RESOURCE';
export const ASSIGNMENT_DELETE_RESOURCE = 'ASSIGNMENT_DELETE_RESOURCE';

