export const FRIEND_LIST_REQUEST = 'FRIEND_LIST_REQUEST';
export const FRIEND_LIST_SUCCESS = 'FRIEND_LIST_SUCCESS';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';
export const FRIEND_FAIL = 'FRIEND_FAIL';
export const GET_PENDING_FRIEND_REQUEST = 'GET_PENDING_FRIEND_REQUEST';
