export const GET_GROUP = 'GET_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';

export const GROUP_ADD_RESOURCE = 'GROUP_ADD_RESOURCE';
export const GROUP_EDIT_RESOURCE = 'GROUP_EDIT_RESOURCE';
export const GROUP_DELETE_RESOURCE = 'GROUP_DELETE_RESOURCE';
