export const GET_LESSONS = 'GET_LESSONS';
export const EDIT_LESSONS = 'EDIT_LESSONS';
export const DELETE_LESSONS = 'DELETE_LESSONS';

export const LESSONS_ADD_RESOURCE = 'LESSONS_ADD_RESOURCE';
export const LESSONS_EDIT_RESOURCE = 'LESSONS_EDIT_RESOURCE';
export const LESSONS_DELETE_RESOURCE = 'LESSONS_DELETE_RESOURCE';
