export const GET_LESSON = 'GET_LESSON';
export const GET_OLD_LESSON = 'GET_LESSON';
export const EDIT_LESSON = 'EDIT_LESSON';
export const DELETE_LESSON = 'DELETE_LESSON';

export const LESSON_ADD_RESOURCE = 'LESSON_ADD_RESOURCE';
export const LESSON_EDIT_RESOURCE = 'LESSON_EDIT_RESOURCE';
export const LESSON_DELETE_RESOURCE = 'LESSON_DELETE_RESOURCE';

export const LESSON_ADD_ASSIGNMENT = 'LESSON_ADD_ASSIGNMENT ';
export const LESSON_EDIT_ASSIGNMENT  = 'LESSON_EDIT_ASSIGNMENT ';
export const LESSON_DELETE_ASSIGNMENT = 'LESSON_DELETE_ASSIGNMENT ';