export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_ADD_GROUP = "USER_ADD_GROUP";
export const USER_ADD_RESOURCE = "USER_ADD_RESOURCE";
export const USER_EDIT_RESOURCE = "USER_EDIT_RESOURCE";
export const USER_DELETE_RESOURCE = "USER_DELETE_RESOURCE";

export const USER_ADD_LESSON = "USER_ADD_LESSON";
export const USER_EDIT_LESSON = "USER_EDIT_LESSON";
export const USER_DELETE_LESSON = "USER_DELETE_LESSON";

export const USER_ADD_ASSIGNMENT = "USER_ADD_ASSIGNMENT";
export const USER_EDIT_ASSIGNMENT = "USER_EDIT_ASSIGNMENT";
export const USER_DELETE_ASSIGNMENT = "USER_DELETE_ASSIGNMENT";
export const USER_DELETE_SHARED_ASSIGNMENT = "USER_DELETE_SHARED_ASSIGNMENT";

export const USER_GET_SHARED_GROUPS = "USER_GET_SHARED_GROUPS";
export const USER_DELETE_SHARED_GROUP = "USER_DELETE_SHARED_GROUP";
export const USER_GET_SHARED_RESOURCES = "USER_GET_SHARED_RESOURCES";
export const USER_DELETE_SHARED_RESOURCE = "USER_DELETE_SHARED_RESOURCE";

export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
