export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAIL = 'USER_FAIL';

export const USERGROUPS_REQUEST = 'USERGROUPS_REQUEST';
export const USERGROUPS_SUCCESS = 'USERGROUPS_SUCCESS';
export const USERGROUPS_FAIL = 'USERGROUPS_FAIL';
