import React, { useReducer , useState, useEffect} from 'react';
import { createUserAction } from '../../redux/actions/userActions';
import { useDispatch, useSelector } from 'react-redux';
import axios from 'axios';
import AuthButtons from '../AuthButtons/AuthButtons';
import FormInput from '../Form-Input/Form-Input';
import { ReactComponent as Logo } from '../../assets/fox.svg';

import {
	SignUpSection,
	SignUpContainer,
	HeaderContainer,
	HeaderText,
	OrContainer,
	OrBorder,
	OrText,
	Form,
	SignUpButton,
	LoginMessage,
	InputRow,
	InputItem,
	ErrorMessage,
	TagSelector,
	TagSet,
	SelLi,
	SelList,
	TagList,
	TagContainer
} from './SignUp.elements';

import { Link } from '../../styles';

const initialState = {
	firstName       : '',
	lastName        : '',
	userName        : '',
	email           : '',
	password        : '',
	confirmPassword : ''
};

function reducer(state, { field, value }) {
	return {
		...state,
		[field] : value
	};
}

const SignUpComponent = () => {
	const [ state, dispatch ] = useReducer(reducer, initialState);
	const { firstName, lastName, userName, email, password, confirmPassword } = state;

	const storeDispatch = useDispatch();
	const { loading, error } = useSelector((state) => state.userAuth);
    let  pTags =[,"WATER",,"COMMUNITY",,"AMERICANSTUDIES","EDITING","PROJECTMANAGER","SEARCHING","ETHNICITY","EQUATIONS","LANGUAGESTUDY","GAMES","REACTIONS","WILLS","BOOKS","BILLS","SICKNESS","PAINTING","MYTHOLOGY","DIGITALTOOLS","MODERNHISTORY","TOXINS","EXPRESSION","PUBLICRELATIONS","POPULARCULTURE","NATIONAL","SOFTWARE","BROADCAST","ONLINE","EXECUTIVESUMMARY","PSYCHOLOGY","MEDICINE","OPERATIONS","MORALITY","PROBLEMSOLVING","EMOTION","WORKSHOPS","BALLET","STOCKS","ANCIENT","METAPHYSICS","ECOMMERCE","GENDER","AFRICA","SOCIALPROBLEMS","HEDGEFUNDS","AMERICAN","DRAWING","SPANISHAMERICAN","MOVIES","OOP","GRAPHICDESIGN","POLITICAL","COMPUTATIONS","CORPORATE","COMPUTERS","DATAMINING","SIGHTREADING","FEDERALRESERVE","NETWORK","MODERN","MASTERS","BASEBALL","PERCUSSION","RESEARCH","PARASITES","FICTION","DEVELOPMENT","SOCIALDISINTEGRATION","COMPUTERSCIENCE","DATABASES","ORCHESTRA","COMPUTER","STRENGTH","DATAMANAGEMENT","SENIORYEAR","NATURE","TODAY","INORGANIC","CULTURES","PHILOSOPHY","SWIM","HANDBELL","ROBOTICS","PEOPLE","TECHNOLOGY","SELFDEVELOPMENT","JUNIOR","PUBLICOPINIONS","DIVERSEPOPULATIONS","VOCALS","PRISONERS","FUNDAMENTALCONCEPTS","INNOVATION","BRANDS","ADMINISTRATION","CALCULUS","CURRENTISSUES","REASONING","PIANO","ECONOMICS","POLITICALSCIENCE","SUPPLYCHAIN","REPORT","IDENTITY","RELIGION","CRIME","FREEWILL","CORPORATELAW","WOMEN","LEGALISSUE","SINGING","BEETHOVEN","RACE","VALUES","CAREER","ALGORITHMS","GOVERNMENT","STORIES","MICROBIOLOGY","GENDERSTUDIES","PUBLICPOLICY","PARTICLES","PANTHEON","POLITICALTHOUGHT","REGULATIONSS","CLASSICAL","AMERICA","ENGLISH","SYMPHONIC","ANIMALS","MEDIASTUDIES","VIDEO","FEMINISM","ADOLESCENCE","LANGUAGE","MANHOOD","DRAMA","DIGIALMEDIA","ARABIC","COGNITIVE","LATINAMERICAN","HUMANBEHAVIOR","GLOBALSTUDIES","ORGANISMS","MOBILE","CONDUCT","GROUPS","LETLANG","INVERTEBRATE","DEVICES","JESUS","JOURNALIST","MECHANICALCHEMISTRY","LABOR","FRESHWATER","INTERACTIVE","ADVERTISING","SCHUBERT","HISPANICCARIBBEAN","SLEEPPSYCHOLOGY","FINITESTRUCTURES","PATIENT","FOOD","RELATIONS","REVOLUTION","ATTACK","FUNDAMENTALS","BUSINESSLAW","FEED","INTERNATIONALSTUDIES","ABNORMAL","VOLLEYBALL","ADDICTIONS","SHAKESPEARE","EQUITIES","DIGITALMEDIA","CHRISTIANITY","FIGHT","LABORRELATIONS","SEX","CIVILIZATIONS","ASIA","PREJUDICE","LOVE","JUSTICE","US","CRITICALHISTORY","TRAIN","SPRINGBOARD","COLONIAL","LATINAMERICA","TESTING","INFORMATIONTECHNOLOGY","FILM","SOCIAL","FASHIONDESIGN","TYPESCRIPT","DOCUMENTARY","JOB","NATURAL","PROJECT","SHEETS","MUSCLE","SOCIALSERVICE","COMPENTANCY","ABROAD","TOOLBOX","STRATEGY","FOREIGNLANGAUGE","PYTHON","RETAIL","LINGUISTICS","WIRELESS","ATHLETICS","PORTFOLIO","TAX","THOUGHT","SYNTAX","DISCRETEMATHEMATICS","FASHION","CAPPING","TAX FINANCE","PREVENTION","REGULATIONS","WORDS","DANCE","MULTICAMERA","PROFESSIONALISSUES","SMOKE","BUSINESSADMINISTRATION","PUBLICLIFE","STATUS","SOCIALMEDIA","STRAIN","SCIENTIFICSTUDY","PRINCIPLES","PHOTOGRAPHY","BEHAVIORS","FEMINIST","ETHICS","METHODS","RECOVER","AUDITING","MATH","BATTLE","ARCHERY","BORDER","INTENSIVE","EUROPEANSTUDIES","GREEK","SPIRTUALITY","IMPLEMENTATION","FOOTBALL","COACHING","SPORTS","THEMES","LICENSING","CHEMISTY","SPANISHCINEMA","GEOLOGY","EVENTPLANNING","ECONOMIC","PERSPECTIVES","TRADING","HONORS","MARKETS","EUROPE","VIEWS","JUDAEOCHRISTIAN","GODS","BALANCE","PRACTICAL","FLYFISHING","COUNTING","NEWYORK","SWIMMING","MICROSCOPY","HUMANFACTORS","PROCESS","POPULATION","INTERVIEW","SEMINARS","COOK","COSMOLOGY","BACKGROUND","ADULT","FAMILYLAW","OPERATIONALMODELS","MANGEMENT","HUMANBODY","STRUCTURE","DIGITAL","SECURITY","COMPARISON","PSYCHOBIOLOGY","JAPAN","ENSEMBLE","EARTH","COMMUNITYSOCIOLOGY","GOALS","PUBLIC","TOOLS","OBJECTIVES","CHARACTER","CRIMINALS","LIBERATION","INTERNATIONALTRADING","PERSONALITY","TABLES","STYLE","CHORAL","PRAGMATISM","CIVILLITIGATION","DISEASE","CELLSTRUCTURE","MATHPRACTICUM","SOCIOLOGY","WORK","COMPOSITION","SCREENWRITING","ANALYTICS","TECHNIQUES","MATHEMATICALANALYSIS","ENVIRONMENT","PROGRAMMING","PRESS","DETAIL","HURT","PRINCIPLE","POLUTION","WELLBEING","SYMBOLICLOGIC","FLUTE","ENGINEERING","LAB","CRITICISM","BIOLOGY","POLITICS","BANKING","GENERAL","JAZZ","ZOS","FOUNDATIONS","EXCEL","SUPPLYANDDEMAND","PHYSICAL","ENTREPRENEURSHIP","CATHOLICS","CLINICAL","CATHOLICSTUDIES","GAME","TELEVISION","OPERATINGSYSTEMS","BIOCHEMISTRY","GAMEDESIGN","ITALIANAMERICAN","CLOUD","DEVELOPINGAREAS","NEWS","FEE","REPORTING","ARTISTICTASTE","CONTRACT","TRANSLATION","FORMS","DATAVISUALIZATION","HACKING","FAITH","RECONSTRUCTION","COMPUTERENGINEERING","DIGITALGRAPHICS","IDEAL","TOPICS","CRIMINALJUSTICE","NUTRITION","COMMERCE","SPEAKING","PREFERENCES","REPRESENTATION","VISUAL","HUMAN","PATTERNS","PHYSIOLOGY","AESTHETICS","BABY","MIND","FIRMS","PRODUCT","WOODWIND","GRAPHICS","ACCOUNTING","PUBLICAFFAIRS","DOMESTICVIOLENCE","PROFESSIONALSTUDIES","PLANT","LOGIC","PEACE","MOVE","DATASCIENCE","PHYSICSSCIENCE","SOCIALETHICS","ITALY","FINANCIALMANAGEMENT","LETTER","READING","COUNSELING","INFIELD. EXPERIENCE","WRITERS","ATHLETICTRAINING","LITERATURE","THEORY","HELP","ANIMATION","NOVELS","MANAGMENT","BODY","POETRY","OPERTATINGSYSTEMS","MENTALPROCESSES","LINEARALGEBRA","DATAPREDICTION","SURVEY","POLLING","WEIGHT","FINANCE","VISUALIZATION","SPAIN","WEBSITE","CARBON","RELIGIOUSSOCIOLOGY","FENCING","LEADERSHIP","ROCKS","SCHOOL","COMPLEXANALYSIS","CHARTS","ELEMENTARY","DIPLOMATIC","DEATH","LITERACY","MARGINALIZEDCOMMUNITIES","ARTIFICIALINTELLIGENCE","IRISH","MORAL","JUVENILEDELINQUENCY","DATA","BACTERIA","BRASS","VIRUSES","WORLDRELIGIONS","PHP","TRENDS","JAPANESE","PERSONALGROWTH","BREAK","SCRIPT","OPERA","MISSION","INSTRUMENTAL","SITUATIONS","STORY","CODING","CSS","SALES","FRENCH","CHINA","DNA","MORALS","MOVING","PHYSICALEDUCATION","LIFESPAN","CHILDREN","SAFETY","STATISTICS","BAROQUE","DISEASEPREVENTION","RADIO","CONSCIOUSNESS","SUSTAINABILITY","WAR","ENVIORNMENT","HISTORY","GUIDE","AUDIO","EXPERIMENTAL","FOUNDATIONAL","ALGEBRA","PERSONAL","MARKETING","CIVILIZATION","SCRIPTURES","CONSIDERATION","PSYCHOBIOLOGICAL","STATE","SKILLS","LAW","CIVILWAR","TRADE","HTML","POEMS","ROME","EARTHSCIENCE","QUANTUMMECHANICS","DREAM","ECOSYSTEM","INTERNATIONAL","GOLF","ROCKANDROLL","SOCIALCHANGE","PRESIDENCY","RELATIONSHIP","NURSE","MONITOR","EUROPEAN","CAUSE","BLOOD","EASTERNSTUDIES","SOCCER","GOSPEL","NETWORKING","TRADITIONAL","ARCHAEOLOGY","NAPOLEAN","LEGAL","ORGANIZATIONS","PROCESSES","TEAM","CHOIR","LEAD","STRATEGIES","TEMPERATURE","INDEPENDENT","ENVIRONMENTAL","DISCIPLESHIP","DESIGN","BANKS","SOCIALINEQUALITY","CONTEMPORARY","ART","EVENT","INEQUALITY","ALCOHOLISM","ENVIRONMENTALPLANNING","SCRATCH","SYSTEMS","CONGRESSTODAY","HUMANITIES","COMPUTINGTECHNOLOGY","COMPUTATIONAL","TITLESEARCH","DIFFERENTIALEQUATIONS","SCUBADIVING","FOREIGNLANGUAGE","SENIOR","PACE","TEACHER","CULTURE","GEOMETRY","SOCIALTHEORY","CURRENT","INVESTING","FIELDWORK","WRITNG","EAST","SKIN","SOCIALWORK","BIBLE","TWIST","PLAY","MEDIA","CAREERDEVELOPMENT","PERCEPTION","CAPPNG","RELIGIOUS","GLOBAL","GOLDENAGE","PROJECTMANAGEMENT","FISH","WORLD","CPR","SQL","DATACOLLECTION","THEORIES","MOTIONPICTURE","MEDICAL","LATIN","CAPTURE","BEAUTYPRINCIPLES","R","CAPSTONE","PRODUCTION","WORLDSTUDIES","PRECALCULUS","GLOBALISSUES","BONDS","PROGRESS","STUDY","QUERY","EVIDENCE","DIET","PUBLICHEALTH","BODILYFUNCTIONS","FAMILYSTUDIES","EVOLUTION","PREDICTIVE","AFRICANAMERICAN","CHEMISTRY","CRITICALREADING","INSTRUMENT","CHEMICALS","PRICES","MAGAZINES","STONES","GUITAR","CONVERSATION","EXPERIENCE","INFORMATIONSYSTEMS","WESTERNSTUDIES","ARTIFACTS","CHINESE","CELLS","FUNGI","CREATIVE","SOUNDS","SCULPTING","SPEECH","HISPANIC","MEASUREMENT","SOCIETY","MICRO","UNIX","CONDITIONING","BUSINESS","ANALYTIC","MUSICINDUSTRY","PROGNOSIS","CHART","LOCAL","ORGANIC","MORTGAGE","IMMUNESYSTEM","ARM","INPERSON","FILTERING","TECHONOLOGY","ECONOMICEQUALITY","SHOT","PLANNING","THESIS","ARTICLES","KARATE","CHAMBER","HARM","PHYSICS","BLACKHISTORY","MACHINELEARNING","DEBUGGING","COMPUTERGRAPHICS","MARX","JOURNALISM","EXERCISE","APPLIEDSTATISTICS","QUANTITATIVE","SPANISH","BRANDING","MERCHANDISE","PRAXIS","THEATRE","PROFESSIONAL","WRITING","SPIRITUALITY","INFRASTRUCTURE","VOCALSKILLS","HEALTH","BEGINNING","HUMANS","SINGINGVOCALS","STOMACH","MODELUNITEDNATIONS","ARGUMENTS","EMPLOYMENT","PRISON","NOVEL","RELATIONSHIPS","CASHFLOWS","LIFE","PUBLICPRESENTATION","DIFFERENCES","ENVIRONMENTALSCIENCE","LEARNING","ACTING","SAVE","PHILOSOPHICAL","COMMUNICATIONS","ESTATES","ACTIVE","CATHOLIC","ANATOMY","RACQUETBALL","PRACTICE","REALITY","CREATIVITY","SAILING","WORKPLACE","BELIEFSYSTEMS","WRITTENANALYSIS","INTERNSHIP","IMMIGRATION","ENERGY","SAVINGS","RUN","BOXING","GERMAN","ZOO","ASIANSTUDIES","SCRIPTS","CINEMA","BUSINESSMANAGEMENT","EDUCATIONSOCIOLOGY","JUNIORFIELDEDUCATION","MEN","CONSUMER","GRAMMAR","TALKING","HUMANRESOURCES","SHOWS","FILMMAKING","IT","RESOURCES","INDIA","TRANSFER","SPECIALTOPICS","HERITAGESPEAKERS","THINKING","UNUSUALPATTERNS","DEMAND","JUDAISM","FAMILY","BEHAVIOR","TRUSTS","SUPERVISEDRESEARCH","POLICY","WEALTH","CRTICIALTHINKING","CRUST","RENAISSANCE","FIRSTYEAR","VIETNAM","COMMUNICATION","MUSIC","JOINT","BONE","EVENTS","ATOMS","PROCEDURES","ELEMENTARYTOPOLOGY","KNITWEAR","CLOUDCOMPUTING","ACTORS","REALPROPERTY","AMERICANHISTORY","POPULAR","CRIMINAL","RIGHTS","CHURCH","CYBERSECURITY","EVALUATION","CONCEPTS","PHILOSOPHYMONEY","ENVIRONMENTALSTUDIES","ANALYSIS","INTERNET","PLANTCELLS","EXCEPTIONALCHILD","SUBSTANCES","SOFTWAREDEVELOPMENT","GROWTH","THEOLOGY","CAMPAIGN","CHAPEL","SHORTSTORIES","RELATIVE","CULTURAL","SICK","MONEY","JUVENILELAW","OPERATIONCHAIN","EXISTENTIALISM","ESSAY","DIVING","EDUCATION","SOCIALENVIRONMENTS","PUBLICSPEAKING","INTRODUCTION","FDR","SEMINAR","BASKETBALL","STORYTELLING","OLDLITERATURE","TAXES","GREECE","ISSUES","VOTING","FRANCE","CRITICALTHINKING","WORKSHOP","PRESENTATION","EASTERNSTUDIES SOCIETY","COMMUNISM","SINGERS","EDUCATIONAL","CALCULATIONS","INSTITUTIONS","COMBINATORICS","WEBDESIGN","ECONOMY","TREATMENT","ORGANIZATION","BRITISH","MATHEMATICS","CASH","STUDIES","TEACHING","SCIENCE","DEBATE","PURCHASE","HEAT","PERFORMANCE","INTRODUCTORY","MOLECULES","TENNIS","MEDIEVAL","COLLEGE","WORLDHISTORY","VISUALS","MOVEMENTS","TECHNICAL","DATAANALYSIS","MOVEMENT","DIRECTING","DRUG","AFRICANPOLITICS","PRESENTATIONS","IBM","ORAL","ELECTRONICMEDIA","ABSTRACTALGEBRA","FIGURES","CAMERA","WOMENSTUDIES","FORENSICS","DRUGS","PROBABILITY","NFORMATIONSYSTEMS","STUDYTOUR","INTERNAL","ITALIAN","FILMSTUDIES","LENS","CONFLICT","INTERMEDIATE","COMPILERS","PLANTS","NUMERICALANALYSIS","COPYWRITING","CUTLURE","EATERNSTUDIES","MANAGEMENT","CARIBBEAN","WORLD STUDIES","JAVA","POSTPRODUCTION","COST","GAMING","CHANGE","DRUGABUSE","ELEMENTS","DATABASE","DIGITALDESIGN","FIELDEXPERIENCE","ECOLOGY","SOCIALDEVIANCE","YOGA","CATHOLICTHOUGHT","OPERATINSYSTEMS","RELIGIOUSSTUDIES","ADVANCED","COMPILING","DISCRIMINATION","RULES","WIND","HUMANSTUDIES","SUPPLY","SORTING","GENRE"];
	const [tagSet, updateTagStats] = useState([]);
	const tags = pTags.sort();
	const [updating, setUpdating] = useState("");
	
	const handleSubmit = async (e) => {
		e.preventDefault();

		if (!firstName || !lastName || !email || !userName || !password) {
			console.log('Please fill out all fields');
			return;
		}

		if (password !== confirmPassword) {
			console.log('Password must match');
			return;
		}

		const firstNameCapitalized =
			firstName.charAt(0).toUpperCase() + firstName.toLowerCase().slice(1);

		const lastNameCapitalized =
			lastName.charAt(0).toUpperCase() + lastName.toLowerCase().slice(1);

		const newUserObject = {
			firstname : firstNameCapitalized,
			lastname  : lastNameCapitalized,
			email     : email,
			username  : userName,
			hashpw    : password
		};
		const payLoad = {username: userName, tags: tagSet};
		axios.post("http://96.249.211.3:105/setUserTags",payLoad);
		storeDispatch(createUserAction(newUserObject));
	};

	const handleChange = (e) => {
		dispatch({ field: e.target.name, value: e.target.value });
	};

	

	const toggleTag  = (tag) =>{
		if(tagSet.indexOf(tag) != -1){
			let tSet = tagSet.filter(t => t != tag);
			updateTagStats(tSet);
			console.log("here11");
		}else if(tagSet.length <3){
			let tempSet = tagSet;
			tempSet[tagSet.length] = tag;
			updateTagStats(tempSet);
			console.log("here222");
		}else{
			alert("Thanks for the extra info! Although Outfox has a limit for personal tags. Please try to bring your tag list down to three items. ");
		}
	};


	
	const TList = ()=>{
		
		if(tags){
			return (
				
				<TagList style={{display: 'inline-block'}}>
				<h3>Select 3 tags that best describe your interests.</h3>
				<ul>
		
				{tags.map((tag) => {
					if(tagSet.indexOf(tag) != -1){
						//return(<SelLi><button key={tag} onClick={() => {makeTagChange(tag)}}>{tag}</button></SelLi>);
					}else{
						return(<li><button key={tag} onClick={() =>{makeTagChange(tag)}}>{tag}</button></li>);
					}
				})}
				</ul>
				</TagList>
			);
		}else{
			return (<li>{"loading tags"}</li>);
		}
	};
	const SList =() => {
		if(tags){
			return (
				
				<SelList style={{display: 'inline-block'}}>
					<h3>Selected tags:</h3>
					<ul>
						{tagSet.map((tag) => {return(<li><button key={tag} onClick={() =>{makeTagChange(tag)}}>{tag}</button></li>)})}
					</ul>
				</SelList>
				
				
				)
		}else{
			return (<li>{"loading tags"}</li>); 
		}
	}

	const makeTagChange = (tag) =>{
		setUpdating(tag);
	}

	
	useEffect(() => {
		
		if(updating != ""){
			toggleTag(updating)
		}
		setUpdating(false);

	}, [updating]);
















	return (
		<SignUpSection>
			<SignUpContainer>
				<HeaderContainer>
					<Logo />
					<HeaderText>Outfox</HeaderText>
				</HeaderContainer>
				<AuthButtons />
				<OrContainer>
					<OrBorder />
					<OrText>Or</OrText>
					<OrBorder />
				</OrContainer>
					<TagContainer>
					<TList />
					<SList />

					</TagContainer>
				
				
					
				
				
				<Form onSubmit={handleSubmit}>
					{error && <ErrorMessage>Username already exists</ErrorMessage>}
					<InputRow>
						<InputItem>
							<FormInput
								label="First Name"
								name="firstName"
								type="text"
								value={firstName}
								onChange={handleChange}
								required
							/>
						</InputItem>
						<InputItem>
							<FormInput
								label="Last Name"
								name="lastName"
								type="text"
								value={lastName}
								onChange={handleChange}
								required
							/>
						</InputItem>
					</InputRow>
					<InputRow>
						<InputItem>
							<FormInput
								label="Username"
								name="userName"
								type="text"
								value={userName}
								onChange={handleChange}
								required
							/>
						</InputItem>
						<InputItem>
							<FormInput
								label="Email"
								name="email"
								type="email"
								value={email}
								onChange={handleChange}
								required
							/>
						</InputItem>
					</InputRow>
					<InputRow>
						<InputItem>
							<FormInput
								label="Password"
								name="password"
								type="password"
								value={password}
								onChange={handleChange}
								required
							/>
						</InputItem>
						<InputItem>
							<FormInput
								label="Confirm Password"
								name="confirmPassword"
								type="password"
								value={confirmPassword}
								onChange={handleChange}
								required
							/>
						</InputItem>
					</InputRow>
				
					<SignUpButton type="submit" disabled={loading}>
						Create a free account
					</SignUpButton>
				</Form>
				<LoginMessage>
					Already have an Outfox account? <Link to="signin">Log in</Link>
				</LoginMessage>
			</SignUpContainer>
		</SignUpSection>
	);
};

export default SignUpComponent;
